"""adiciona restricao unica de horario

Revision ID: 2a15acf7eee4
Revises: 9c03a87e24b8
Create Date: 2026-06-11 14:24:36.126674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a15acf7eee4'
down_revision: Union[str, Sequence[str], None] = '9c03a87e24b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_agendamentos_slot_exato', ['barbearia_slug', 'profissional', 'data', 'horario'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_agendamentos_slot_exato', type_='unique')

    # ### end Alembic commands ###
