"""cria schema inicial

Revision ID: 9c03a87e24b8
Revises: 
Create Date: 2026-06-11 14:16:38.689106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c03a87e24b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_slug', sa.String(), nullable=True),
    sa.Column('cliente_nome', sa.String(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('horario', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('profissional', sa.String(), nullable=True),
    sa.Column('telefone_cliente', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_barbearia_slug'), ['barbearia_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_id'), ['id'], unique=False)

    op.create_table('barbearias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('plano_ativo', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbearias_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_barbearias_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barbearias_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_barbearias_slug'), ['slug'], unique=True)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_slug', sa.String(), nullable=True),
    sa.Column('hora_abertura', sa.Integer(), nullable=True),
    sa.Column('hora_fechamento', sa.Integer(), nullable=True),
    sa.Column('cor_tema', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cor_fundo', sa.String(), nullable=True),
    sa.Column('instrucoes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_barbearia_slug'), ['barbearia_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuracoes_id'), ['id'], unique=False)

    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_slug', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profissionais_barbearia_slug'), ['barbearia_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_profissionais_id'), ['id'], unique=False)

    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_slug', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_barbearia_slug'), ['barbearia_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_id'))
        batch_op.drop_index(batch_op.f('ix_servicos_barbearia_slug'))

    op.drop_table('servicos')
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profissionais_id'))
        batch_op.drop_index(batch_op.f('ix_profissionais_barbearia_slug'))

    op.drop_table('profissionais')
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_id'))
        batch_op.drop_index(batch_op.f('ix_configuracoes_barbearia_slug'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbearias_slug'))
        batch_op.drop_index(batch_op.f('ix_barbearias_nome'))
        batch_op.drop_index(batch_op.f('ix_barbearias_id'))
        batch_op.drop_index(batch_op.f('ix_barbearias_email'))

    op.drop_table('barbearias')
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_barbearia_slug'))

    op.drop_table('agendamentos')
    # ### end Alembic commands ###
