"""adiciona branding e consentimento whatsapp

Revision ID: ae48cc9dec24
Revises: 2a15acf7eee4
Create Date: 2026-06-14 19:11:42.617092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae48cc9dec24'
down_revision: Union[str, Sequence[str], None] = '2a15acf7eee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aceita_promocoes_whatsapp', sa.Boolean(), nullable=True))

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_publico', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logomarca_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_comercial', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('site_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_maps_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mensagem_publica', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('captar_whatsapp_lembretes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('captar_whatsapp_promocoes', sa.Boolean(), nullable=True))
        batch_op.drop_column('cor_fundo')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cor_tema')
        batch_op.drop_column('instrucoes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrucoes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cor_tema', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cor_fundo', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('captar_whatsapp_promocoes')
        batch_op.drop_column('captar_whatsapp_lembretes')
        batch_op.drop_column('mensagem_publica')
        batch_op.drop_column('google_maps_url')
        batch_op.drop_column('site_url')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('whatsapp_comercial')
        batch_op.drop_column('logomarca_url')
        batch_op.drop_column('nome_publico')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('aceita_promocoes_whatsapp')

    # ### end Alembic commands ###
