"""corrige colunas de branding e whatsapp

Revision ID: ae70d6cd4bfa
Revises: ae48cc9dec24
Create Date: 2026-06-14 19:48:39.700674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae70d6cd4bfa'
down_revision: Union[str, Sequence[str], None] = 'ae48cc9dec24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aceita_lembrete_whatsapp', sa.Boolean(), nullable=True))

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_tema', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cor_fundo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instrucoes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('instrucoes')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cor_fundo')
        batch_op.drop_column('cor_tema')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('aceita_lembrete_whatsapp')

    # ### end Alembic commands ###
